"""Self-contained local web interface.

The page deliberately uses a restrained document-like visual language.  It
never combines the four independent methods into an overall authorship
verdict, and it consumes compact per-method SSE events rather than a monolithic
JSON response.
"""

HTML_PAGE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>osu! Beatmap AI Detector</title>
<style>
:root{--ink:#20242a;--muted:#69717b;--line:#c9cdd2;--soft:#f5f6f7;--paper:#fff;--blue:#2c5f87;--red:#a32222;--orange:#ad4c12;--yellow:#806100;--grey:#59616b;--bluegrey:#50677a;--ok:#2f6a45}
*{box-sizing:border-box}html{color-scheme:light}body{margin:0;background:#eceeef;color:var(--ink);font:14px/1.5 system-ui,-apple-system,"Segoe UI","Microsoft YaHei",sans-serif}
button,input,select,textarea{font:inherit;color:inherit}.skip-link{position:absolute;left:-9999px}.skip-link:focus{left:12px;top:8px;background:#fff;border:1px solid #222;padding:8px;z-index:20}
.app-header{background:#222930;color:#fff;border-bottom:4px solid #54718b}.header-inner{max-width:1420px;margin:auto;padding:18px 24px}.app-header h1{font-size:21px;margin:0 0 3px}.app-header p{margin:0;color:#cbd3da}
.layout{max-width:1420px;margin:0 auto;padding:20px 24px 36px}.setup{background:var(--paper);border:1px solid var(--line);display:grid;grid-template-columns:minmax(280px,1fr) minmax(420px,1.4fr)}
.setup section{padding:20px}.setup section+section{border-left:1px solid var(--line)}h2{font-size:17px;margin:0 0 14px}h3{font-size:15px;margin:0}.subtle{color:var(--muted)}
.drop{border:1px dashed #7f8790;background:#fafafa;padding:22px;text-align:center;cursor:pointer}.drop:focus,.drop.drag{outline:2px solid var(--blue);outline-offset:2px}.drop strong{display:block;font-size:16px;margin-bottom:4px}
.file-summary{margin:10px 0 0;padding:0;list-style:none;max-height:112px;overflow:auto}.file-summary li{padding:4px 0;border-bottom:1px solid #eee}.audio-row{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:12px;align-items:center}.audio-row input{min-width:0}.warning{display:none;margin-top:9px;border-left:4px solid #b06d00;background:#fff6df;padding:8px 10px;color:#604500}.warning.show{display:block}.error-box{display:none;margin-top:10px;border-left:4px solid var(--red);background:#fff0f0;padding:9px}.error-box.show{display:block}
.method-list{border-top:1px solid var(--line)}.method-option{display:grid;grid-template-columns:22px 1fr;gap:7px;padding:11px 4px;border-bottom:1px solid var(--line);align-items:start}.method-option input{margin-top:3px}.method-option b{display:block}.method-option span{display:block;color:var(--muted);font-size:13px;margin-top:1px}.dependency{font-size:12px;color:#725d10;margin-top:3px;display:none}.dependency.show{display:block}
.controls{display:flex;gap:10px;align-items:end;flex-wrap:wrap;margin-top:16px}.field label{display:block;color:var(--muted);font-size:12px;margin-bottom:3px}.field select{height:36px;border:1px solid #8f969e;background:#fff;padding:0 28px 0 8px}.primary,.secondary{height:36px;border:1px solid #26313a;padding:0 16px;cursor:pointer}.primary{background:#26313a;color:#fff}.primary:hover{background:#111820}.primary:disabled{background:#92979c;border-color:#92979c;cursor:not-allowed}.secondary{background:#fff}.secondary:hover{background:#f0f1f2}
details.advanced{margin-top:13px;border-top:1px solid var(--line);padding-top:9px}details.advanced summary{cursor:pointer;color:var(--muted)}textarea{width:100%;min-height:90px;margin-top:8px;border:1px solid #999;padding:8px;resize:vertical}
.job{display:none;margin-top:18px;background:#fff;border:1px solid var(--line)}.job.show{display:block}.job-head{display:grid;grid-template-columns:1fr auto;gap:12px;padding:14px 16px;border-bottom:1px solid var(--line);align-items:center}.job-head strong{display:block}.job-actions{display:flex;gap:7px;flex-wrap:wrap}.job-actions a,.job-actions button{color:var(--blue);background:#fff;border:1px solid #9aa2aa;padding:5px 9px;text-decoration:none;cursor:pointer}.progress-track{height:8px;background:#dfe2e5}.progress-fill{height:100%;background:#426b8c;width:0;transition:width .2s}.progress-meta{display:flex;gap:15px;color:var(--muted);font-size:12px;margin-top:3px}
.results-layout{display:grid;grid-template-columns:320px minmax(0,1fr);margin-top:18px;border:1px solid var(--line);background:#fff;min-height:480px}.map-panel{border-right:1px solid var(--line)}.map-tools{padding:12px;border-bottom:1px solid var(--line)}.map-tools select{width:100%;border:1px solid #999;background:#fff;padding:7px}.map-list{list-style:none;margin:0;padding:0;max-height:700px;overflow:auto}.map-row{display:grid;grid-template-columns:1fr auto;gap:8px;width:100%;border:0;border-bottom:1px solid #ddd;background:#fff;text-align:left;padding:11px 12px;cursor:pointer}.map-row:hover{background:#f6f7f8}.map-row.active{background:#e9eef2;border-left:4px solid #365e7d;padding-left:8px}.map-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.map-version{display:block;color:var(--muted);font-size:12px}.method-dots{display:flex;gap:4px;align-items:center}.dot{width:8px;height:8px;border:1px solid #777;background:#eee}.dot.red{background:var(--red)}.dot.orange{background:var(--orange)}.dot.yellow{background:#d0a400}.dot.grey{background:#8b9198}.dot.bluegrey{background:var(--bluegrey)}.dot.running{background:#fff;border:2px solid var(--blue)}.dot.disabled{background:#fff;border-color:#bbb}
.result-panel{padding:18px;min-width:0}.map-title{padding-bottom:12px;border-bottom:2px solid #30373e;margin-bottom:14px}.map-title h2{margin:0 0 2px;font-size:19px}.method-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.method-card{border:1px solid #aeb4ba;border-top:4px solid #7c858e;background:#fff;min-width:0}.method-card.red{border-top-color:var(--red)}.method-card.orange{border-top-color:var(--orange)}.method-card.yellow{border-top-color:#c79b00}.method-card.bluegrey{border-top-color:var(--bluegrey)}.card-head{padding:13px 14px 10px;border-bottom:1px solid #ddd}.card-head p{margin:3px 0 0;color:var(--muted);font-size:12px}.metric{padding:14px}.metric-main{display:flex;align-items:baseline;gap:10px;flex-wrap:wrap}.percent{font-size:31px;line-height:1;font-weight:680;letter-spacing:-.5px}.fact-value{font-size:24px;font-weight:680}.state{font-weight:650}.state.red{color:var(--red)}.state.orange{color:var(--orange)}.state.yellow{color:var(--yellow)}.state.grey{color:var(--grey)}.state.bluegrey{color:var(--bluegrey)}.measurements{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-top:13px}.measurement{border-left:2px solid #c5c9cd;padding-left:7px;min-width:0}.measurement small{display:block;color:var(--muted)}.measurement span{display:block;font-variant-numeric:tabular-nums;overflow:hidden;text-overflow:ellipsis}
.ruler{height:24px;position:relative;margin:13px 1px 0;border-bottom:2px solid #9da4aa}.ruler .value{position:absolute;bottom:-5px;width:3px;height:15px;background:#1d4e73}.ruler .mark{position:absolute;bottom:-3px;width:1px;height:10px;background:#a04918}.ruler-labels{display:flex;justify-content:space-between;color:var(--muted);font-size:11px;margin-top:3px}
.card-status{padding:13px 14px;color:var(--muted)}.card-status .spinner{display:inline-block;width:11px;height:11px;border:2px solid #b4bac0;border-top-color:var(--blue);border-radius:50%;animation:spin .8s linear infinite;margin-right:6px}@keyframes spin{to{transform:rotate(360deg)}}
.reasons{border-top:1px solid #ddd}.reasons summary{cursor:pointer;padding:10px 14px;font-weight:600}.reason-guide{margin:0;padding:0 14px 9px;color:var(--muted);font-size:12px}.reason-list{list-style:none;padding:0 14px 10px;margin:0}.reason-list li{display:grid;grid-template-columns:1fr auto;gap:8px;padding:7px 0;border-top:1px solid #eee}.reason-label{border-bottom:1px dotted #777;cursor:help}.reason-observation{display:block;color:var(--muted);font-size:12px;margin-top:2px}.reason-value{font-variant-numeric:tabular-nums;color:var(--orange);border-bottom:1px dotted #a66b47;cursor:help;align-self:center}.empty-reason{color:var(--muted)}.technical{border-top:1px solid #eee;padding:9px 14px;color:var(--muted);font-size:12px}.technical summary{cursor:pointer}.technical dl{display:grid;grid-template-columns:auto 1fr;gap:3px 9px}.technical dt{font-weight:600}.technical dd{margin:0;overflow-wrap:anywhere}.technical a{color:var(--blue)}
.empty-state{padding:60px 20px;text-align:center;color:var(--muted)}.footnote{max-width:1420px;margin:16px auto 0;color:#6b7279;font-size:12px}.toast{position:fixed;right:18px;bottom:18px;background:#252b30;color:#fff;border-left:4px solid #6e92ae;padding:10px 14px;display:none;max-width:360px}.toast.show{display:block}
[data-tooltip]{position:relative}[data-tooltip]:hover:after,[data-tooltip]:focus:after{content:attr(data-tooltip);position:absolute;left:0;bottom:calc(100% + 6px);z-index:10;width:min(330px,80vw);background:#20252a;color:#fff;padding:7px 9px;font-size:12px;font-weight:400;white-space:normal}
@media(max-width:900px){.setup{grid-template-columns:1fr}.setup section+section{border-left:0;border-top:1px solid var(--line)}.results-layout{grid-template-columns:1fr}.map-panel{border-right:0;border-bottom:1px solid var(--line)}.map-list{display:flex;max-height:none;overflow:auto}.map-row{min-width:220px;border-right:1px solid #ddd}.method-grid{grid-template-columns:1fr}}
@media (max-width: 680px){.layout,.header-inner{padding-left:12px;padding-right:12px}.setup section{padding:14px}.result-panel{padding:12px}.method-grid{gap:10px}.measurements{grid-template-columns:1fr}.job-head{grid-template-columns:1fr}.percent{font-size:27px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}.progress-fill{transition:none}.spinner{animation:none}}
</style>
</head>
<body>
<a class="skip-link" href="#main">Skip to main content</a>
<header class="app-header"><div class="header-inner"><h1>osu! Beatmap AI Detector</h1><p>Four independent checks, reported separately with no overall verdict.</p></div></header>
<main class="layout" id="main">
  <div class="setup">
    <section aria-labelledby="inputTitle">
      <h2 id="inputTitle">1. Select beatmaps</h2>
      <div id="dropZone" class="drop" role="button" tabindex="0" aria-label="Select or drop beatmap files">
        <strong>Drop .osu or .osz files here</strong><span class="subtle">You can also click to select multiple files</span>
      </div>
      <input id="mapFiles" type="file" accept=".osu,.osz,.zip" multiple aria-label="Select beatmap files" hidden>
      <ul id="fileSummary" class="file-summary" aria-live="polite"></ul>
      <div class="audio-row"><input id="audioFile" type="file" accept=".mp3,.ogg,.wav,.flac,.m4a,.aac"><label for="audioFile" class="subtle">Optional audio</label></div>
      <p class="subtle">Inside an OSZ, audio is resolved only by the exact relative <code>AudioFilename</code>. If that path is missing, select the audio manually; similarly named files are never guessed.</p>
      <div id="audioError" class="error-box" role="alert"></div>
      <details class="advanced"><summary>Paste one .osu file as text</summary><textarea id="modePaste" aria-label="Paste one osu beatmap as text" placeholder="Paste the complete .osu text here"></textarea></details>
    </section>
    <section aria-labelledby="methodTitle">
      <h2 id="methodTitle">2. Select checks</h2>
      <div class="method-list">
        <label class="method-option"><input type="checkbox" name="method" value="source" checked><span><b>Source Provenance Check</b><span>Checks explicit AI-use disclosures and exact matches to registered files.</span></span></label>
        <label class="method-option"><input id="whiteboxMethod" type="checkbox" name="method" value="whitebox" checked><span><b>Mapperatorinator Model Agreement</b><span>Runs the original Mapperatorinator models and measures agreement with their generation process. Requires audio and takes longer.</span><em id="whiteboxDependency" class="dependency show">This check depends on candidate intervals from Mapping Structure Check, which is therefore enabled automatically.</em></span></label>
        <label class="method-option"><input type="checkbox" name="method" value="forensic" checked><span><b>Generator Trace Check</b><span>Checks coordinates, timing, SV, and file formatting for mechanical generation traces.</span></span></label>
        <label class="method-option"><input id="contentMethod" type="checkbox" name="method" value="content" checked disabled><span><b>Mapping Structure Check</b><span>Compares rhythm, movement, and object arrangement with the human reference set.</span></span></label>
      </div>
      <div class="controls">
        <div class="field"><label for="device">Model-agreement device</label><select id="device"><option value="auto">Auto (prefer CUDA)</option><option value="cuda">CUDA</option><option value="cpu">CPU</option></select></div>
        <button id="startButton" class="primary" type="button">Start analysis</button>
      </div>
      <div id="computeWarning" class="warning" role="status">Mapperatorinator Model Agreement needs CUDA for practical performance. CPU execution is supported but may be extremely slow.</div>
      <p class="subtle">Model-agreement work is checkpoint-major: each model is loaded once and processes the whole batch. Results stream to the page per beatmap and per check.</p>
      <details class="advanced"><summary>Local task cache</summary><p class="subtle">Completed derived model-agreement results are reused only when input, model, and protocol hashes match. The default limit is 20 GiB; original uploads are not retained.</p><button id="clearCache" class="secondary" type="button">Clear task cache</button></details>
    </section>
  </div>

  <section id="jobPanel" class="job" aria-busy="false" aria-labelledby="jobTitle">
    <div class="job-head"><div><strong id="jobTitle">Analysis job</strong><span id="jobMessage" class="subtle" role="status" aria-live="polite">Preparing</span><div class="progress-meta"><span id="progressCount">0 / 0</span><span id="progressStage">Waiting</span></div></div><div class="job-actions"><a id="htmlExport" hidden>Download HTML report</a><a id="jsonExport" hidden>Download technical JSON</a><button id="cancelButton" type="button">Cancel job</button></div></div>
    <div class="progress-track" role="progressbar" aria-label="Analysis progress" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div id="progressFill" class="progress-fill"></div></div>
  </section>

  <section class="results-layout" aria-label="Analysis results">
    <aside class="map-panel"><div class="map-tools"><label for="mapFilter" class="subtle">Filter beatmaps</label><select id="mapFilter"><option value="all">All</option><option value="abnormal">At least one anomaly</option><option value="fact">Provenance match</option><option value="running">Running</option><option value="unable">Unavailable</option></select></div><ul id="mapList" class="map-list"></ul></aside>
    <div class="result-panel"><div id="resultEmpty" class="empty-state">Select beatmaps and start an analysis. Results will appear here as each check finishes.</div><div id="resultView" hidden><header class="map-title"><h2 id="selectedTitle"></h2><div id="selectedMeta" class="subtle"></div></header><div id="methodGrid" class="method-grid"></div></div></div>
  </section>
  <p class="footnote">This tool runs locally. An anomaly percentile is a rank relative to the human reference set, not an AI-authorship probability. “Below alert threshold” does not establish human authorship. Protocol and model details are available under Technical details.</p>
</main>
<div id="toast" class="toast" role="status" aria-live="polite"></div>
<script>
(()=>{'use strict';
const METHODS=['source','whitebox','forensic','content'];
const COPY={source:['Source Provenance Check','Checks explicit AI-use disclosures and exact matches to registered files.'],whitebox:['Mapperatorinator Model Agreement','Runs the original Mapperatorinator models and measures agreement with their generation process. Requires audio and takes longer.'],forensic:['Generator Trace Check','Checks coordinates, timing, SV, and file formatting for mechanical generation traces.'],content:['Mapping Structure Check','Compares rhythm, movement, and object arrangement with the human reference set.']};
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={files:[],maps:new Map(),selected:0,methods:[...METHODS],selectedMethods:[...METHODS],jobId:null,events:null,cuda:null,whiteboxAvailable:null};
const drop=$('dropZone'), fileInput=$('mapFiles'), audio=$('audioFile'), whitebox=$('whiteboxMethod'), content=$('contentMethod');
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),4500)}
function setFiles(files){state.files=[...files];$('fileSummary').innerHTML=state.files.map(f=>`<li>${esc(f.name)} <span class="subtle">${(f.size/1024).toFixed(1)} KiB</span></li>`).join('')||'<li class="subtle">No files selected</li>'}
drop.onclick=()=>fileInput.click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fileInput.click()}};fileInput.onchange=()=>setFiles(fileInput.files);
for(const name of ['dragenter','dragover'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('drag')});for(const name of ['dragleave','drop'])drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('drag')});drop.addEventListener('drop',e=>setFiles(e.dataTransfer.files));
function syncDependency(){if(whitebox.checked){content.checked=true;content.disabled=true;$('whiteboxDependency').classList.add('show')}else{content.disabled=false;$('whiteboxDependency').classList.remove('show')}syncComputeWarning()}
function syncComputeWarning(){const enabled=whitebox.checked;const box=$('computeWarning');if(state.whiteboxAvailable===false){box.textContent='The lightweight environment is missing model-agreement dependencies. Use the full audio-review launcher; CPU mode also requires the complete environment.'}else{box.textContent='Mapperatorinator Model Agreement needs CUDA for practical performance. CPU execution is supported but may be extremely slow.'}const warn=state.whiteboxAvailable===false||$('device').value==='cpu'||state.cuda===false;box.classList.toggle('show',enabled&&warn)}
whitebox.onchange=syncDependency;$('device').onchange=syncComputeWarning;
fetch('/api/health').then(r=>r.json()).then(h=>{state.cuda=!!(h.compute&&h.compute.cuda_available);state.whiteboxAvailable=!!(h.whitebox&&h.whitebox.available);syncComputeWarning()}).catch(()=>{});
function chosenMethods(){return [...document.querySelectorAll('input[name=method]:checked')].map(i=>i.value)}
function ensureMap(index,payload={}){if(!state.maps.has(index)){const methods={};state.methods.forEach(m=>{const enabled=state.selectedMethods.includes(m);methods[m]={method:m,name:COPY[m][0],description:COPY[m][1],state:enabled?'running':'disabled',label:enabled?'Running':'Disabled',tone:enabled?'running':'disabled',reasons:[]}});state.maps.set(index,{index,path:payload.path||`Beatmap ${index+1}`,title:payload.title||'',version:payload.version||'',creator:payload.creator||'',methods})}const map=state.maps.get(index);for(const k of ['path','title','version','creator'])if(payload[k])map[k]=payload[k];return map}
function mapVisible(map){const f=$('mapFilter').value;if(f==='all')return true;const cards=Object.values(map.methods);if(f==='abnormal')return cards.some(c=>['near','elevated','high','match'].includes(c.state));if(f==='fact')return map.methods.source&&map.methods.source.state==='match';if(f==='running')return cards.some(c=>c.state==='running');if(f==='unable')return cards.some(c=>c.state==='unable');return true}
function renderMapList(){const maps=[...state.maps.values()].filter(mapVisible);$('mapList').innerHTML=maps.map(map=>{const name=map.title||map.path;const dots=state.methods.map(m=>`<i class="dot ${esc((map.methods[m]||{}).tone||'disabled')}" title="${esc(COPY[m][0])}"></i>`).join('');return `<li><button class="map-row ${map.index===state.selected?'active':''}" data-index="${map.index}"><span class="map-name">${esc(name)}<span class="map-version">${esc(map.version||map.creator||'')}</span></span><span class="method-dots">${dots}</span></button></li>`}).join('');document.querySelectorAll('.map-row').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.index);renderAll()})}
function number(v,d=4){return typeof v==='number'&&Number.isFinite(v)?v.toFixed(d):'—'}
function scoreNumber(v){if(typeof v!=='number'||!Number.isFinite(v))return '—';if(v>0&&v<1&&1-v<0.00005)return v.toFixed(10).replace(/0+$/,'');return v.toFixed(4)}
function thresholdEntries(card){return Object.entries(card.thresholds||{}).sort((a,b)=>a[1]-b[1])}
function ruler(card){if(typeof card.score!=='number')return '';const ts=thresholdEntries(card),max=Math.max(1,card.score,...ts.map(x=>x[1]))*1.04;const marks=ts.map(([name,v])=>`<i class="mark" style="left:${Math.min(100,v/max*100)}%" title="${esc(name)} ${scoreNumber(v)}"></i>`).join('');return `<div class="ruler" aria-hidden="true"><i class="value" style="left:${Math.min(100,card.score/max*100)}%"></i>${marks}</div><div class="ruler-labels"><span>0</span><span>${number(max,3)}</span></div>`}
function reasons(card){const rows=card.reasons||[];const guide=rows.length?'<p class="reason-guide">Ranked by effect on the anomaly score, not by raw value. The meaning of 0 and 1 differs between metrics; hover for details.</p>':'';const body=rows.length?`<ul class="reason-list">${rows.slice(0,5).map(r=>{const impact=typeof r.contribution==='number'?`Raises ${r.contribution>=0?'+':''}${number(r.contribution)}`:'Impact unavailable';const tip=esc(r.detail||'');return `<li><span><span class="reason-label" tabindex="0" data-tooltip="${tip}">${esc(r.label)}</span><small class="reason-observation">${esc(r.observation||'Raw value '+(typeof r.value==='number'?number(r.value):r.value??'—'))}</small></span><span class="reason-value" tabindex="0" data-tooltip="${tip}">${impact}</span></li>`}).join('')}</ul>`:'<div class="reason-list empty-reason">No sufficiently strong individual anomaly indicators</div>';return `<details class="reasons"><summary>Decision details (${rows.length})</summary>${guide}${body}</details>`}
function technical(card,map){const tech=card.technical||{};const rows=Object.entries(tech).filter(([,v])=>v!==null&&v!==undefined).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('');return `<details class="technical"><summary>Technical details</summary><dl>${rows||'<dt>Status</dt><dd>No additional information</dd>'}</dl>${state.jobId?`<a href="/api/jobs/${state.jobId}/results/${map.index}" target="_blank">View or download this beatmap’s complete technical JSON</a>`:''}</details>`}
function pendingCard(method){return `<article class="method-card"><header class="card-head"><h3>${esc(COPY[method][0])}</h3><p>${esc(COPY[method][1])}</p></header><div class="card-status"><span class="spinner"></span>${method==='whitebox'?'Waiting for every model and interval':'Waiting for computation'}</div></article>`}
function cardHtml(card,map){if(!card||card.state==='running')return pendingCard(card?card.method:'source');if(card.state==='disabled')return `<article class="method-card"><header class="card-head"><h3>${esc(card.name)}</h3><p>${esc(card.description)}</p></header><div class="card-status">Disabled</div></article>`;const cls=esc(card.tone||'grey');let metric='';if(card.kind==='fact'){metric=`<div class="metric-main"><span class="fact-value">${esc(card.label)}</span></div><div class="measurements"><div class="measurement"><small>Registered file</small><span>${card.exact_registry_match?'Exact match':'No match'}</span></div><div class="measurement"><small>AI disclosure</small><span>${card.explicit_disclosure?'Explicitly present':'Not found'}</span></div></div>`}else{const pct=typeof card.percentile==='number'?`${card.percentile.toFixed(2)} <small>percentile</small>`:'—';const ts=thresholdEntries(card);metric=`<div class="metric-main"><span class="percent" tabindex="0" data-tooltip="${esc(card.percentile_notice||'Anomaly percentile relative to the human reference set; this is not the probability of AI authorship.')}">${pct}</span><span class="state ${cls}">${esc(card.label)}</span></div><div class="measurements"><div class="measurement" tabindex="0" data-tooltip="Internal anomaly score compared with this method’s calibrated thresholds. Higher is generally more anomalous, but this is not an AI probability."><small>Model score</small><span>${scoreNumber(card.score)}</span></div>${ts.slice(0,2).map(([n,v])=>`<div class="measurement" tabindex="0" data-tooltip="The model score must be strictly greater than this calibrated threshold to enter the corresponding anomaly level. Extra digits prevent values close to 1 from being misrepresented as 1.0000."><small>${n.toLowerCase().includes('high')?'High-anomaly threshold':'Anomaly threshold'}</small><span>${scoreNumber(v)}</span></div>`).join('')}</div>${ruler(card)}`}
return `<article class="method-card ${cls}"><header class="card-head"><h3>${esc(card.name)}</h3><p>${esc(card.description)}</p></header><div class="metric">${metric}</div>${reasons(card)}${technical(card,map)}</article>`}
function renderResult(){const map=state.maps.get(state.selected);if(!map){$('resultEmpty').hidden=false;$('resultView').hidden=true;return}$('resultEmpty').hidden=true;$('resultView').hidden=false;$('selectedTitle').textContent=map.title||map.path;$('selectedMeta').textContent=[map.version,map.creator].filter(Boolean).join(' · ');$('methodGrid').innerHTML=state.methods.map(m=>cardHtml(map.methods[m],map)).join('')}
function renderAll(){renderMapList();renderResult()}
$('mapFilter').onchange=renderMapList;
function applyMethod(card){const map=ensureMap(Number(card.index),card);map.methods[card.method]=card;if(!state.maps.has(state.selected))state.selected=Number(card.index);renderAll()}
function updateProgress(p){$('jobMessage').textContent=p.message||p.phase||'';$('progressFill').style.width=`${Math.max(0,Math.min(100,p.percent||0))}%`;const track=document.querySelector('[role=progressbar]');track.setAttribute('aria-valuenow',String(p.percent||0));$('progressCount').textContent=`${p.completed_units||0} / ${p.total_units||0}`;$('progressStage').textContent=p.current_checkpoint?`${p.phase} · ${p.current_checkpoint}`:p.phase||''}
function connect(job){if(state.events)state.events.close();const es=new EventSource(job.events_url);state.events=es;es.addEventListener('method_result',e=>applyMethod(JSON.parse(e.data)));es.addEventListener('progress',e=>updateProgress(JSON.parse(e.data)));es.addEventListener('item_error',e=>toast(JSON.parse(e.data).error||'One beatmap failed'));es.addEventListener('failed',e=>{const p=JSON.parse(e.data);toast(p.progress?.message||'Job failed');finish(false)});es.addEventListener('cancelled',()=>{toast('Job cancelled; completed results remain available');finish(false)});es.addEventListener('complete',e=>{updateProgress(JSON.parse(e.data).progress||{});toast('Analysis complete');finish(true);es.close()});es.onerror=()=>{if($('jobPanel').getAttribute('aria-busy')!=='true')es.close()}}
function finish(ok){$('jobPanel').setAttribute('aria-busy','false');$('startButton').disabled=false;$('cancelButton').disabled=true;if(ok){$('htmlExport').hidden=false;$('jsonExport').hidden=false}}
async function start(){const pasted=$('modePaste').value.trim();if(!state.files.length&&!pasted){toast('Select or paste at least one beatmap first');return}state.selectedMethods=chosenMethods();if(!state.selectedMethods.length){toast('Select at least one check');return}const fd=new FormData();state.files.forEach(f=>fd.append('files',f,f.name));if(pasted)fd.append('files',new Blob([pasted],{type:'text/plain'}),'pasted.osu');if(audio.files[0])fd.append('audio',audio.files[0],audio.files[0].name);const white=state.selectedMethods.includes('whitebox');fd.append('selected_methods',JSON.stringify(state.selectedMethods));fd.append('content_model_enabled',String(state.selectedMethods.includes('content')));fd.append('forensic_model_enabled',String(state.selectedMethods.includes('forensic')));fd.append('revision_registry_enabled',String(state.selectedMethods.includes('source')));fd.append('fusion_model_enabled','false');fd.append('include_features','false');fd.append('whitebox_config',JSON.stringify({enabled:white,checkpoints:['v29','v30','v31','v32','v32-mini'],device:$('device').value,precision:'bf16',forward_batch_size:1,discriminator_enabled:white,deep_fusion_enabled:false}));$('audioError').classList.remove('show');$('startButton').disabled=true;$('cancelButton').disabled=false;$('jobPanel').classList.add('show');$('jobPanel').setAttribute('aria-busy','true');$('htmlExport').hidden=true;$('jsonExport').hidden=true;state.maps.clear();state.selected=0;renderAll();
try{const response=await fetch('/api/jobs',{method:'POST',body:fd});const data=await response.json();if(!response.ok){const detail=data.detail||data;const message=typeof detail==='string'?detail:(detail.message||JSON.stringify(detail));if(detail.code==='manual_audio_selection_required'){$('audioError').textContent=message+' Requested file(s): '+(detail.requested_audio||[]).join(', ');$('audioError').classList.add('show');audio.focus()}throw new Error(message)}state.jobId=data.job_id;$('htmlExport').href=`/api/jobs/${data.job_id}/report.html`;$('jsonExport').href=`/api/jobs/${data.job_id}/report.json`;connect(data)}catch(err){toast(err.message||'Unable to create the job');finish(false)}}
$('startButton').onclick=start;$('cancelButton').onclick=async()=>{if(state.jobId){await fetch(`/api/jobs/${state.jobId}`,{method:'DELETE'});$('cancelButton').disabled=true}};$('clearCache').onclick=async()=>{const response=await fetch('/api/cache',{method:'DELETE'});toast(response.ok?'Task cache cleared':'Unable to clear the task cache')};setFiles([]);syncDependency();
})();
</script>
</body></html>'''
